class Event < ApplicationRecord
    belongs_to :entity
    belongs_to :user

    def self.labelsino(dato)
        if dato == 0 ; 'NO'
        elsif dato == 1 ; 'SI'
        end 
    end 

    def self.ransackable_attributes(auth_object = nil)
        ["date_new", "user_id", "entity_id", "work_accident", "mortal_accident", "occupational_disease",]
    end 

    def self.accidentes_mortales(entity)
        accidentes_mortales = 0
        año = Time.now.year
        events = Event.where("entity_id = ? ", entity) if entity.present?
        if events.present?
            events.each  do |event| 
                accidentes_mortales += 1 if event.date_new.present? && event.date_new.strftime("%Y").to_i == año && event.mortal_accident == 1   
            end
        end
        return accidentes_mortales
    end    
 
    def self.accidentes_trabajo(entity)
        accidentes_trabajo = 0
        año = Time.now.year
        events = Event.where("entity_id = ? ", entity) if entity.present?
        if events.present?
            events.each  do |event| 
                accidentes_trabajo += 1 if event.date_new.present? && event.date_new.strftime("%Y").to_i == año  && event.work_accident == 1
            end
        end
        return accidentes_trabajo
    end   
    

    def self.label_affected_body(dato)
        if dato == 0 ; 'Sin clasificar'
        elsif dato == 1 ; 'Cerebro'
        elsif dato == 2 ; 'Oído (s)  externo'
        elsif dato == 3 ; 'Oído (s)  interno (incluyendo la audición)'
        elsif dato == 4 ; 'Ojo (s) (incluye nervios ópticos y visión)'
        elsif dato == 5 ; 'Párpado'
        elsif dato == 6 ; 'Mandíbula (incluyendo el mentón)'
        elsif dato == 7 ; 'Boca (incluye labios, diente, lengua, garganta y sentido del gusto)'
        elsif dato == 8 ; 'Mejilla'
        elsif dato == 9 ; 'Nariz (incluye fosas nasales, senos y sentido del olfato)'
        elsif dato == 10 ; 'Ceja'
        elsif dato == 11 ; 'Cara, partes múltiples (cualquier combinación de las partes arriba citadas)'
        elsif dato == 12 ; 'Cara, no identificada en otra parte'
        elsif dato == 13 ; 'Cuero cabelludo'
        elsif dato == 14 ; 'Cráneo (incluye solamente lesiones óseas de la bóveda y la base craneal sin compromiso cerebral'
        elsif dato == 15 ; 'Cabeza, múltiple, cualquier combinación de las partes anteriores'
        elsif dato == 16 ; 'Cabeza no identificada en otra parte'
        elsif dato == 17 ; 'Cuello (incluye columna cervical y médula espinal correspondiente)'
        elsif dato == 18 ; 'Brazo'
        elsif dato == 19 ; 'Hombro'
        elsif dato == 20 ; 'Codo'
        elsif dato == 21 ; 'Antebrazo'
        elsif dato == 22 ; 'Extremidades superiores (cualquier combinación de las partes anteriores)'
        elsif dato == 23 ; 'Extremidades superiores (arriba de la muñeca), no identificada en otra parte'
        elsif dato == 24 ; 'Muñecas'
        elsif dato == 25 ; 'Mano (excluyendo la muñeca y los dedos)'
        elsif dato == 26 ; 'Mano,  incluyendo dedos'
        elsif dato == 27 ; 'Dedo (s)'
        elsif dato == 28 ; 'Extremidades superiores, múltiples (cualquier combinación de las partes anteriores)'
        elsif dato == 29 ; 'Extremidades superiores, múltiples (cualquier combinación de las partes anteriores)'
        elsif dato == 30 ; 'Abdomen (incluye órganos internos y sus hernias)'
        elsif dato == 31 ; 'Espalda (incluye músculos de la espalda, columna, dorso lumbar, región lumbar y médula espinal)'
        elsif dato == 32 ; 'Tórax (incluye costillas, esternón y órganos internos del tórax)'
        elsif dato == 33 ; 'Caderas (incluye pelvis, órganos pélvicos y nalgas,  escroto, coxis, pubis, sacro, ilíaco y órganos genitales)'
        elsif dato == 34 ; 'Hombros (incluye axila)  región escapular,  omoplato y clavícula'
        elsif dato == 35 ; 'Tronco, múltiples (cualquier combinación de las partes anteriores)'
        elsif dato == 36 ; 'Tronco,  no identificada en otra parte'
        elsif dato == 37 ; 'Muslo'
        elsif dato == 38 ; 'Rodilla (incluye región poplítea),  corva'
        elsif dato == 39 ; 'Pierna  (entre la rodilla y el tobillo)'
        elsif dato == 40 ; 'Extremidades inferiores múltiples (cualquier combinación de las partes anteriores)'
        elsif dato == 41 ; 'Extremidades inferiores,  no identificadas en otra parte (arriba del tobillo)'
        elsif dato == 42 ; 'Tobillos'
        elsif dato == 43 ; 'Pié (excluyendo tobillo y dedos)'
        elsif dato == 44 ; 'Dedo(s) o  artejos'
        elsif dato == 45 ; 'Extremidades inferiores,  múltiples  (cualquier combinación de las partes anteriores)'
        elsif dato == 46 ; 'Extremidades inferiores no identificadas en otra parte'
        elsif dato == 47 ; 'Parte múltiples  (se aplica cuando se ha afectado más de una de las partes principales del cuerpo,  tales como,  un brazo, una pierna)'
        elsif dato == 48 ; 'Sistemas orgánicos (Se aplica cuando la totalidad de un sistema orgánico ha sido afectado, sin lesión específica en ninguna otra parte, como en el caso de intoxicación,  acción corrosiva que afecte órganos internos,  lesión de centros nerviosos, etc.  No se aplica cuando el daño en el sistema es producido por una lesión externa, que afecta una parte externa, tal como una lesión en la espalda que incluye daño a los nervios de la medula espinal)'
        elsif dato == 49 ; 'Sistema circulatorio  (corazón, sangre, arterias, venas,  etc.)'
        elsif dato == 50 ; 'Sistema digestivo'
        elsif dato == 51 ; 'Sistema excretorio (riñones, vejiga, intestinos, etc.)'
        elsif dato == 52 ; 'Sistema músculo-esquelético  (huesos, articulaciones, tendones, músculos, etc.'
        elsif dato == 53 ; 'Sistema nervioso'
        elsif dato == 54 ; 'Sistema respiratorio (pulmones, etc.)'
        elsif dato == 55 ; 'Varios sistemas orgánicos'
        elsif dato == 56 ; 'Otros sistemas orgánicos'
        elsif dato == 57 ; 'Partes del cuerpo,  no identificadas en otra parte'
        elsif dato == 58 ; 'Sin clasificar (insuficiente información para identificar la parte afectada)'
        end 
    end  
    

    def self.label_type_injure(dato)
        if dato == 0 ; 'Sin clasificar'
        elsif dato == 1 ; 'Amputación o enucleación'
        elsif dato == 2 ; 'Asfixia, estrangulación, ahogamiento'
        elsif dato == 3 ; 'Quemadura (calórica) incluye eritema'
        elsif dato == 4 ; 'Quemadura  (química) incluye eritema'
        elsif dato == 5 ; 'Inflamación de vías respiratorias  (por agentes químicos)'
        elsif dato == 6 ; 'Concusión cerebral'
        elsif dato == 7 ; 'Enfermedad infecciosa o contagiosa -Ántrax, brucelosis, tuberculosis, etc.'
        elsif dato == 8 ; 'Contusión, machacón, magulladura, conservándose la superficie de la piel intacta; traumatismo, atrición, hematoma, edema y equimosis traumáticos'
        elsif dato == 9 ; 'Vesículas  (ampollas)'
        elsif dato == 10 ; 'Cortada, laceración, pinchazo, herida abierta, avulsión, sección, desprendimiento y fractura de las uñas'
        elsif dato == 11 ; 'Dermatitis-erupción, inflamación de la piel o tejido subcutáneo, incluyendo pústulas, etc.'
        elsif dato == 12 ; 'Luxación, esguince'
        elsif dato == 13 ; 'Choque eléctrico, electrocución, quemadura eléctrica'
        elsif dato == 14 ; 'Fractura, fisura ósea'
        elsif dato == 15 ; 'Congelación, lesión cutánea producida por el frío y otros efectos de la exposición a bajas temperaturas'
        elsif dato == 16 ; 'Pérdida de la audición o su deterioro (como lesión separada no como secuela de otra lesión)'
        elsif dato == 17 ; 'Insolación, calambres calóricos, agotamiento o postración por calor y otros efectos del calor ambiental.  No incluye quemaduras solares u otros efectos de radiaciones'
        elsif dato == 18 ; 'Hernias, ruptura.  Incluye tanto las hernias inguinales como no inguinales'
        elsif dato == 19 ; 'Inflamación o irritación de las articulaciones, tendones o músculos. Incluye bursitis, sinovitis, tenosinovitis, etc.  No incluye distensiones o desgarros de músculos y tendones o sus consecuencias'
        elsif dato == 20 ; 'Envenenamiento (sistémico)'
        elsif dato == 21 ; 'Neumoconiosis - incluye la de los mineros del carbón, asbestosis, silicosis, etc.'
        elsif dato == 22 ; 'Efectos de las radiaciones, quemaduras solares y toda forma de lesión de los tejidos, huesos o fluidos del cuerpo, producidos por exposición a radiaciones.'
        elsif dato == 23 ; 'Raspaduras, abrasiones (heridas superficiales), conjuntivitis por cuerpo extraño no alojado, excoriación, erosión, fricción.'
        elsif dato == 24 ; 'Lesiones en ojos tales como rayones de córnea, heridas en cristalino'
        elsif dato == 25 ; 'Distensiones, desgarros (incluye lumbalgias por esfuerzo)'
        elsif dato == 26 ; 'Lesiones múltiples'
        elsif dato == 27 ; 'Enfermedad ocupacional no identificada en otra parte.  Hiperqueratosis, neuropatía'
        elsif dato == 28 ; 'Otras lesiones no identificadas en otra parte'
        elsif dato == 29 ; 'Sin clasificar, no determinada'
        end
    end


    def self.label_accident_agent(dato)
        if dato == 0 ; 'Sin clasificar'
        elsif dato == 1 ; 'Personas'
        elsif dato == 2 ; 'Alta presión (como trabajo en un cajón neumático,  zambullida profunda, etc.)'
        elsif dato == 3 ; 'Baja presión (aire enrarecido como en alturas extremas)'
        elsif dato == 4 ; 'Animales.  (Excepto los que siguen)'
        elsif dato == 5 ; 'Pájaros'
        elsif dato == 6 ; 'Insectos'
        elsif dato == 7 ; 'Reptiles'
        elsif dato == 8 ; 'Huesos'
        elsif dato == 9 ; 'Secreciones'
        elsif dato == 10 ; 'Plumas'
        elsif dato == 11 ; 'Pieles, cerdas, lana, etc.  (en estado bruto)'
        elsif dato == 12 ; 'Cueros y pieles curtidas'
        elsif dato == 13 ; 'Productos animales,  no especificados en otra parte'
        elsif dato == 14 ; 'Movimiento del cuerpo (excluyendo levantar, halar, empujar, etc.)'
        elsif dato == 15 ; 'Calderas'
        elsif dato == 16 ; 'Autoclave'
        elsif dato == 17 ; 'Recipientes presurizados (para gases o líquidos),  compresor'
        elsif dato == 18 ; 'Cilindros de oxígeno y acetileno'
        elsif dato == 19 ; 'Líneas de presión  (mangueras o tubos - para líquidos presurizados, gases o vapores)'
        elsif dato == 20 ; 'Recipientes a presión,  no especificados en otra parte'
        elsif dato == 21 ; 'Barriles,  toneles pequeños, tambores,  canecas, baldes'
        elsif dato == 22 ; 'Bultos, paquetes'
        elsif dato == 23 ; 'Cajas, huacales, cartones, canastas'
        elsif dato == 24 ; 'Botellas, cántaros, frascos, etc.'
        elsif dato == 25 ; 'Ampollas'
        elsif dato == 26 ; 'Capilares'
        elsif dato == 27 ; 'Vasos'
        elsif dato == 28 ; 'Tubos de ensayo,  tubos de vidrio'
        elsif dato == 29 ; 'Tanques,  arcones, tolvas, silos, etc.  (No presurizados)'
        elsif dato == 30 ; 'Recipientes,  no especificados en otra parte'
        elsif dato == 31 ; 'Edificios de oficinas, de planta, residenciales, paredes, etc.'
        elsif dato == 32 ; 'Puertas de edificios'
        elsif dato == 33 ; 'Ascensor'
        elsif dato == 34 ; 'Ventana'
        elsif dato == 35 ; 'Puentes'
        elsif dato == 36 ; 'Represas, esclusas, compuertas, etc.'
        elsif dato == 37 ; 'Tribunas, graderías, estadios, etc.'
        elsif dato == 38 ; 'Andamios, tablados, tarimas,  plataformas, etc.'
        elsif dato == 39 ; 'Torres, postes, etc.'
        elsif dato == 40 ; 'Muelles, dársenas, desembarcaderos, etc.'
        elsif dato == 41 ; 'Edificios y estructuras, no especificados en otra parte'
        elsif dato == 42 ; 'Ladrillo'
        elsif dato == 43 ; 'Porcelana, loza.'
        elsif dato == 44 ; 'Tubos de desagüe,  tubos de alcantarilla, revestimiento de chimeneas, etc.'
        elsif dato == 45 ; 'Azulejos (decorativos, no para soportar carga;  mosaicos, etc.)'
        elsif dato == 46 ; 'Alfarería'
        elsif dato == 47 ; 'Mosaicos estructurales (vidriados, comunes o mate).'
        elsif dato == 48 ; 'Artículos de cerámica no especificados en otra parte.'
        elsif dato == 49 ; 'Ácidos'
        elsif dato == 50 ; 'Alcoholes'
        elsif dato == 51 ; 'Alcalis, soda cáustica, cementos, amoníaco, cal, silicato de sodio, etc.'
        elsif dato == 52 ; 'Alcalis, soda cáustica, cementos, amoníaco, cal, silicato de sodio, etc.'
        elsif dato == 53 ; 'Compuestos de Arsénico'
        elsif dato == 54 ; 'Bisulfuro de carbono'
        elsif dato == 55 ; 'Bióxido de carbono'
        elsif dato == 56 ; 'Monóxido de carbono'
        elsif dato == 57 ; 'Cianuro o compuestos cianógenos'
        elsif dato == 58 ; 'Compuestos halogenados, no especificados en otra parte (tricloroetileno, percloroetileno, cloruro de metilo, refrigerantes, flúor, bromo y  yodo)'
        elsif dato == 59 ; 'Compuestos metálicos, no especificados en otra parte (plomo, mercurio, zinc,  bronce, cadmio, cromo, sulfato de aluminio y ferroso.)'
        elsif dato == 60 ; 'Óxidos de nitrógeno  (Humos nitrosos).'
        elsif dato == 61 ; 'Formol'
        elsif dato == 62 ; 'Cidex'
        elsif dato == 63 ; 'Hipocloritos'
        elsif dato == 64 ; 'Sustancias químicas y compuestos químicos no especificados en otras partes'
        elsif dato == 65 ; 'Botas, zapatos, etc.'
        elsif dato == 66 ; 'Polainas'
        elsif dato == 67 ; 'Guantes'
        elsif dato == 68 ; 'Sombreros, elementos para cubrir la cabeza'
        elsif dato == 69 ; 'Sacos o sobretodos, impermeables'
        elsif dato == 70 ; 'Camisas, blusas, suéteres chaquetas'
        elsif dato == 71 ; 'Ternos, pantalones, vestidos, overoles'
        elsif dato == 72 ; 'Medias, para mujer y para hombre'
        elsif dato == 73 ; 'Ropa interior'
        elsif dato == 74 ; 'Vestuario, no especificado en otra parte'
        elsif dato == 75 ; 'Carbón'
        elsif dato == 76 ; 'Coque'
        elsif dato == 77 ; 'ceite crudo, A. C. P. M.'
        elsif dato == 78 ; 'Gasolina, compuestos líquidos de hidrocarburos (parafinas, olefinas, etc.)'
        elsif dato == 79 ; 'Hidrocarburos gaseosos (metano, etano, etileno, propano, butano, isobutano, butileno, isobutileno, gas licuado del petróleo, GLP, etc.) '
        elsif dato == 80 ; 'Querosene o petróleo de uso doméstico'
        elsif dato == 81 ; 'Aceites lubricantes y refrigerantes, grasas'
        elsif dato == 82 ; 'Aceite de cocina'
        elsif dato == 83 ; 'Gases manufacturados'
        elsif dato == 84 ; 'Solventes de nafta (éter de petróleo, extractos minerales, limpiadores de nafta, solventes de caucho, solventes stoddard, solventes aromáticos, toluol etc.'
        elsif dato == 85 ; 'Asfaltos y aceites de petróleo para caminos'
        elsif dato == 86 ; 'Derivados del petróleo y del carbón, no especificados en otra parte'
        elsif dato == 87 ; 'Frío (atmosférico, ambiental)'
        elsif dato == 88 ; 'Transportadores por gravedad'
        elsif dato == 89 ; 'Transportadores de fuerza mecánica'
        elsif dato == 90 ; 'Productos biológicos (sueros, toxinas, antitoxinas, vacunas, plasma, etc.)'
        elsif dato == 91 ; 'Otras medicinas'
        elsif dato == 92 ; 'Motores'
        elsif dato == 93 ; 'Generadores'
        elsif dato == 94 ; 'Transformadores, convertidores'
        elsif dato == 95 ; 'Conductores'
        elsif dato == 96 ; 'Tableros de distribución, barras colectoras, interruptores, fusibles, cortadores de circuitos, cajas de distribución, etc.'
        elsif dato == 97; 'Reóstato, aparatos de arranque y control, condensadores, rectificadores, acumuladores'
        elsif dato == 98 ; 'Aparatos magnéticos y electrolíticos'
        elsif dato == 99 ; 'Artefactos para calefacción'
        elsif dato == 100 ; 'Ventiladores'
        elsif dato == 101 ; 'Aparatos eléctricos, no especificados en otra parte'
        elsif dato == 102 ; 'Estufa'
        elsif dato == 103 ; 'Llamas, fuego, humo'
        elsif dato == 104 ; 'Frutas y sus derivados'
        elsif dato == 105 ; 'Granos y sus derivados'
        elsif dato == 106 ; 'Carnes y sus derivados'
        elsif dato == 107 ; 'Leche y sus derivados'
        elsif dato == 108 ; 'Vegetales y sus derivados'
        elsif dato == 109 ; 'Productos alimenticios, no especificados en otra parte'
        elsif dato == 110 ; 'Gabinetes, archivadores, bibliotecas, etc.'
        elsif dato == 111 ; 'Portahistorias'
        elsif dato == 112 ; 'Incubadora'
        elsif dato == 113 ; 'Sillas, bancas, etc.'
        elsif dato == 114 ; 'Mostradores, bancos de trabajo, etc.'
        elsif dato == 115 ; 'Escritorios'
        elsif dato == 116 ; 'Coberturas para pisos, carpetas, alfombras, esteras, etc.'
        elsif dato == 117 ; 'Equipo para alumbrado, lámparas, bombillas, etc.'
        elsif dato == 118 ; 'Veladoras'
        elsif dato == 119 ; 'Mesas'
        elsif dato == 120 ; 'Camas, camillas'
        elsif dato == 121 ; 'Mesas portátiles'
        elsif dato == 122 ; 'Carrotermo'
        elsif dato == 123 ; 'Mobiliario, muebles, adornos fijos, accesorios, no especificados en otra parte'
        elsif dato == 124 ; 'Artículos de vidrio, no especificados en otra parte. (Cristalería, fibras de vidrio, láminas, etc. - Excluyendo botellas, jarros, frascos o revestimientos de vidrio).'
        elsif dato == 125 ; 'Vidrio'
        elsif dato == 126 ; 'Hachas'
        elsif dato == 127 ; 'Jeringa'
        elsif dato == 128 ; 'Sopletes'
        elsif dato == 129 ; 'Cinceles escoplo, formón'
        elsif dato == 130 ; 'Palancas de hierro, alzaprimas, barras'
        elsif dato == 131 ; 'Limas'
        elsif dato == 132 ; 'Horquillas'
        elsif dato == 133 ; 'Martillo, macho, mandarria, mazo'
        elsif dato == 134 ; 'Hachuelas'
        elsif dato == 135 ; 'Recogedores'
        elsif dato == 136 ; 'Azadones'
        elsif dato == 137 ; 'Cuchillos'
        elsif dato == 138 ; 'Machetes'
        elsif dato == 139 ; 'Bisturí'
        elsif dato == 140 ; 'Picos'
        elsif dato == 141 ; 'Cepillos, garlopas'
        elsif dato == 142 ; 'Alicates, tenazas, pinzas'
        elsif dato == 143 ; 'Brocas'
        elsif dato == 144 ; 'Taladro manual'
        elsif dato == 145 ; 'Punzones'
        elsif dato == 146 ; 'Sogas, cadenas'
        elsif dato == 147 ; 'Microscopio'
        elsif dato == 148 ; 'Serruchos, seguetas, cortavidrios'
        elsif dato == 149 ; 'Tijeras, cizallas'
        elsif dato == 150 ; 'Lapicero'
        elsif dato == 151 ; 'Destornilladores, monta- tornillos'
        elsif dato == 152 ; 'Palas'
        elsif dato == 153 ; 'Traperos'
        elsif dato == 154 ; 'Llaves para tuercas y para tubos'
        elsif dato == 155 ; 'Cuchillas de afeitar'
        elsif dato == 156 ; 'Herramientas manuales, no mecanizadas, no especificadas en otra parte'
        elsif dato == 157 ; 'Esmeriles portátiles y otros con piedras abrasivas'
        elsif dato == 158 ; 'Pulidoras, gratas, brilladoras, enceradoras. (sin piedra abrasiva)'
        elsif dato == 159 ; 'Cinceles'
        elsif dato == 160 ; 'Taladros'
        elsif dato == 161 ; 'Máquina cortadora de tela'
        elsif dato == 162 ; 'Martillos, pisones'
        elsif dato == 163 ; 'Planchadoras'
        elsif dato == 164 ; 'Cuchillos, navajas'
        elsif dato == 165 ; 'Herramientas accionadas con pólvora (Ramset). Armas de fuego'
        elsif dato == 166 ; 'Picadora de verduras'
        elsif dato == 167 ; 'Punzonadoras'
        elsif dato == 168 ; 'Remachadoras'
        elsif dato == 169 ; 'Sopladoras de arena'
        elsif dato == 170 ; 'Sierras'
        elsif dato == 171 ; 'Destornilladores, monta- tornillos'
        elsif dato == 172 ; 'Herramientas para soldar'
        elsif dato == 173 ; 'Herramientas manuales, mecanizadas, no especificadas en otra parte'
        elsif dato == 174 ; 'Calor atmosférico, ambiental (Excluyendo objetos y sustancias calientes)'
        elsif dato == 175 ; 'Equipos de calefacción, no especificados en otra parte. (Hornos, retortas, calentadores de ambiente, estufas, cocinas, etc., que no sean eléctricos)'
        elsif dato == 176 ; 'Greca'
        elsif dato == 177 ; 'Grúas, cabrias'
        elsif dato == 178 ; 'Elevadores, montacargas, ascensores'
        elsif dato == 179 ; 'Palas, dragas'
        elsif dato == 180 ; 'Elevadores neumáticos'
        elsif dato == 181 ; 'Elevadores de cadena, diferencial de cadena'
        elsif dato == 182 ; 'Elevadores eléctricos'
        elsif dato == 183 ; 'Pescante de malacate, malacate de poste o de pértiga'
        elsif dato == 184 ; 'Gatos (mecánicos, hidráulicos, neumáticos, etc.).'
        elsif dato == 185 ; 'Ganchos (para transporte de trozas de madera).'
        elsif dato == 186 ; 'Cubos o cucharones de minería, cangilones'
        elsif dato == 187 ; 'Aparatos de izar, no especificados en otra parte'
        elsif dato == 188 ; 'Agentes infecciosos y parasitarios, no especificados en otra parte. (bacterias, hongos, parásitos, virus, etc. - excluyendo productos químicos, drogas, preparados medicinales o alimentos contaminados)'
        elsif dato == 189 ; 'Escaleras fijas'
        elsif dato == 190 ; 'Escaleras de extensión'
        elsif dato == 191 ; 'Escaleras de paso ancho'
        elsif dato == 192 ; 'Escaleras de mano rectas, sencillas'
        elsif dato == 193 ; 'Escaleras, no especificadas en otra parte'
        elsif dato == 194 ; 'Agua caliente'
        elsif dato == 195 ; 'Corporales'
        elsif dato == 196 ; 'Otros líquidos, no especificados en otra parte'
        elsif dato == 197; 'Agitadores, mezcladoras, volteadores o revolvedoras, etc.'
        elsif dato == 198 ; 'Máquinas agrícolas, no especificadas en otra parte, corta césped'
        elsif dato == 199 ; 'Bruñidoras, pulidoras, lijadoras, esmeriladoras'
        elsif dato == 200 ; 'Máquinas para fundir, forjar y máquinas fijas automáticas para soldar metales'
        elsif dato == 201 ; 'Inyectoras, extrusoras, sopladoras de plásticos'
        elsif dato == 202 ; 'Máquinas trituradoras, pulverizadoras, molinos, etc.'
        elsif dato == 203 ; 'Majadora de carnes'
        elsif dato == 204 ; 'Máquinas para taladrar, barrenar, tornear (roscadora, fresadora y cepilladora para metales, limadora, molinos, rectificadoras)'
        elsif dato == 205 ; 'Máquinas para movimiento de tierra y construcción de carreteras. No especificadas en otra parte'
        elsif dato == 206 ; 'Máquinas para minería y túneles, no especificados en otra parte'
        elsif dato == 207 ; 'Máquinas de oficina'
        elsif dato == 208 ; 'Máquinas empacadoras y envolvedoras, encelofanadoras, etiqueteadoras, abridoras, selladoras'
        elsif dato == 209 ; 'Máquinas recogedoras, peinadoras y cardadoras'
        elsif dato == 210 ; 'Cepilladoras, planeadoras, molduradoras, trompos. (para madera), canteadora, barrenadora para madera)'
        elsif dato == 211 ; 'Prensas, troqueladoras, estampadoras, elaboradoras de puntillas, tapadoras, cadenas, etc., (excepto máquinas de imprenta).'
        elsif dato == 212 ; 'Máquinas de imprenta'
        elsif dato == 213 ; 'Laminadoras, trefiladoras'
        elsif dato == 214 ; 'Sierras, máquinas sinfín, circular'
        elsif dato == 215 ; 'Máquinas tamizadoras y separadoras'
        elsif dato == 216 ; 'Cizallas, cortadoras, rebanadoras. (Cortadoras de disco), guillotinas'
        elsif dato == 217 ; 'Máquinas de coser, hilvanar'
        elsif dato == 218 ; 'Máquinas de tejer, hacer punto o hilar, selfatina, continuas, bobinado'
        elsif dato == 219 ; 'Máquinas, no especificadas en otra parte, básculas'
        elsif dato == 220 ; 'Correas'
        elsif dato == 221 ; 'Cadenas, sogas, cables'
        elsif dato == 222 ; 'Bobinas, poleas, garruchas o roldanas'
        elsif dato == 223 ; 'Embragues de fricción'
        elsif dato == 224 ; 'Engranajes'
        elsif dato == 225 ; 'Aparatos de transmisión de fuerza mecánica, no especificados en otra parte'
        elsif dato == 226 ; 'Artículos de metal, no especificados en otra parte. (Platinas, varillas, alambres, tuercas, pernos, tornillos, puntillas, etc. Incluye metal fundido, lingotes, chatarra fundida, clavos, pero no minerales u otras materias primas en bruto.'
        elsif dato == 227 ; 'Estribos'
        elsif dato == 228 ; 'Metal caliente'
        elsif dato == 229 ; 'Cubetas odontológicas'
        elsif dato == 230 ; 'Agujas'
        elsif dato == 231 ; 'Remaches'
        elsif dato == 232 ; 'Pines'
        elsif dato == 233 ; 'Patos baños'
        elsif dato == 234 ; 'Tapas'
        elsif dato == 235 ; 'Pesas'
        elsif dato == 236 ; 'Latas'
        elsif dato == 237 ; 'Productos minerales, metálicos, no especificados en otra parte. (Productos de minería, en bruto o semi- procesados, tales como minerales en bruto y concentrados de minerales).'
        elsif dato == 238 ; 'Productos minerales, no metálicos, no especificados en otra parte (productos de minería, excavaciones, canteras, etc., tales como. lodo, tierra, arcilla, arena, cascajo, piedra, etc.).'
        elsif dato == 239 ; 'Ruido'
        elsif dato == 240 ; 'Papel y artículos de pulpa, no especificados  en otra parte'
        elsif dato == 241 ; 'Partículas (no identificadas)'
        elsif dato == 242 ; 'Plantas, árboles, vegetación (en condiciones naturales o sin procesar, no incluye granos trillados, frutas, cosechas, troncos con ramas, etc.)'
        elsif dato == 243 ; 'Artículos plásticos, no especificados en otra parte (polvos, láminas, varillas, modelados, etc., pero no las sustancias químicas puras o componentes usados en la fabricación de plásticos), caucho'
        elsif dato == 244 ; 'Artículos de caucho, tapón de gases arteriales'
        elsif dato == 245 ; 'Placa radiográfica'
        elsif dato == 246 ; 'Motores (vapor, combustión interna, etc.).'
        elsif dato == 247 ; 'Bombas. (Compresores de aire incluidos).'
        elsif dato == 248 ; 'Turbinas (hidráulicas, neumáticas, etc.).'
        elsif dato == 249 ; 'Bombas y generadores de energía, no especificados en otra parte'
        elsif dato == 250 ; 'Isótopos y sustancias radioactivas para uso industrial o médico'
        elsif dato == 251 ; 'Radio'
        elsif dato == 252 ; 'Cesio'
        elsif dato == 253 ; 'Combustible para reactor atómico, en bruto o procesado'
        elsif dato == 254 ; 'Desperdicios o desechos radioactivos de reactores atómicos'
        elsif dato == 255 ; 'Radiaciones solares'
        elsif dato == 256 ; 'Equipos de rayos ultravioleta'
        elsif dato == 257 ; 'Equipos de soldadura autógena y eléctrica, arco eléctrico'
        elsif dato == 258 ; 'Equipos de rayos x y fluoroscopia'
        elsif dato == 259 ; 'Sustancias o equipos radioactivos, no especificados en otra parte'
        elsif dato == 260 ; 'Jabones, detergentes, compuestos para limpieza, no especificados en otra parte'
        elsif dato == 261 ; 'Sílice'
        elsif dato == 262 ; 'Desechos industriales, escombros, materiales de desperdicios, no especificados en otra parte'
        elsif dato == 263 ; 'Vapor de agua'
        elsif dato == 264 ; 'Productos textiles, no especificados en otra parte, (Incluye fibras animales después de la primera limpieza o lavado, fibras vegetales y sintéticas- (excepto las de vidrio), hilazas, hilos, mercancías en depósito, fieltros y otros productos textiles'
        elsif dato == 265 ; 'De tracción animal'
        elsif dato == 266 ; 'Aéreos'
        elsif dato == 267 ; 'Vehículos motorizados para carreteras'
        elsif dato == 268 ; 'Bicicletas y otros vehículos no motorizados para carretera'
        elsif dato == 269 ; 'Carritos de mano, plataformas con rodillos y otros vehículos no motorizados'
        elsif dato == 270 ; 'Levantadores de horquilla, montacargas, apiladores, cargadores de madera y otros vehículos cargadores motorizados'
        elsif dato == 271 ; 'Tractores y otros vehículos de remolque motorizados'
        elsif dato == 272 ; 'Vehículos sobre rieles'
        elsif dato == 273 ; 'Trineos y otros vehículos para transporte sobre nieve y hielo'
        elsif dato == 274 ; 'Vehículos acuáticos'
        elsif dato == 275 ; 'Vehículos, no especificados en otra parte'
        elsif dato == 276 ; 'Productos de madera, no especificados en otra parte (Troncos, madera aserrada, tablas, postes, vigas, astillas y otros productos de madera).'
        elsif dato == 277 ; 'Piso (de un edificio, una mina, un vehículo, un andamio, etc.)'
        elsif dato == 278 ; 'Terrenos (al aire libre).'
        elsif dato == 279 ; 'Rampas'
        elsif dato == 280 ; 'Techos'
        elsif dato == 281 ; 'Pasillos o plataformas (superficies elevadas permanentes).'
        elsif dato == 282 ; 'Aceras, senderos, pasillos. (Al aire libre)'
        elsif dato == 283 ; 'Escaleras, escalones. (Que sean parte integral de la edificación)'
        elsif dato == 284 ; 'Calles, caminos, carreteras'
        elsif dato == 285 ; 'Superficies de trabajo, no especificadas en otra parte'
        elsif dato == 286 ; 'Misceláneos, no especificados en otra parte'
        elsif dato == 287 ; 'Equipos de sueros, sondas'
        elsif dato == 288 ; 'Desconocidos, sin identificar (distintos a partículas)'
        end
    end

    def self.label_accident_mechanism(dato)
        if dato == 0 ; 'Sin clasificar'
        elsif dato == 1 ; 'Objetos fijos'
        elsif dato == 2 ; 'Objetos en movimiento'
        elsif dato == 3 ; 'Golpeado contra objetos no especificados'
        elsif dato == 4 ; 'Objetos que caen (incluye personas)'
        elsif dato == 5 ; 'Objetos que vuelan'
        elsif dato == 6 ; 'Golpeado o lesionado por otra persona'
        elsif dato == 7 ; 'Golpeado por, no especificado en otra parte'
        elsif dato == 8 ; 'De andamios, de pasillos,  de plataformas, de sillas,  de techos, etc.'
        elsif dato == 9 ; 'De escaleras'
        elsif dato == 10 ; 'De materiales apilados'
        elsif dato == 11 ; 'De vehículos'
        elsif dato == 12 ; 'En escaleras propias de edificios'
        elsif dato == 13 ; 'Dentro de pozos, excavaciones, aberturas en los pisos, etc.  (Desde el borde la abertura)'
        elsif dato == 14 ; 'Caída a un nivel inferior,  no especificado en otra parte'
        elsif dato == 15 ; 'Caer en el pasillo o en la superficie de trabajo'
        elsif dato == 16 ; 'Caer sobre o contra objetos'
        elsif dato == 17 ; 'Caída a un mismo nivel, no especificada en otra parte'
        elsif dato == 18 ; 'Engranajes, rodillos.'
        elsif dato == 19 ; 'Un objeto movible y uno fijo'
        elsif dato == 20 ; 'Dos o más objetos móviles (que no están engranados)'
        elsif dato == 21 ; 'Materiales aplastantes que pueden derrumbarse en un momento dado (deslizamientos de tierra,  derrumbamiento de edificios, etc.'
        elsif dato == 22 ; 'Dos objetos fijos'
        elsif dato == 23 ; 'Cogido en, debajo o entre, no especificados en otra parte'
        elsif dato == 24 ; 'Por recostarse, arrodillarse o sentarse en objetos (no vibrantes)'
        elsif dato == 25 ; 'Por objetos operados manualmente (no vibrantes)'
        elsif dato == 26 ; 'Por objetos vibrantes'
        elsif dato == 27 ; 'Por materias extrañas en los ojos'
        elsif dato == 28 ; 'Por repetición de presión'
        elsif dato == 29 ; 'Fricción o raspadura no especificada en otra parte'
        elsif dato == 30 ; 'Mordida de persona o de animal'
        elsif dato == 31 ; 'Proveniente de movimientos involuntarios'
        elsif dato == 32 ; 'Proveniente de movimientos voluntarios'
        elsif dato == 33 ; 'Al levantar objetos'
        elsif dato == 34 ; 'Al halar o empujar objetos'
        elsif dato == 35 ; 'Al manipular o lanzar objetos'
        elsif dato == 36 ; 'Sobre- esfuerzo, no especificado en otra parte'
        elsif dato == 37 ; 'Contacto con corriente eléctrica'
        elsif dato == 38 ; 'Altas temperaturas- atmosféricas, o ambientales'
        elsif dato == 39 ; 'Bajas temperaturas- atmosféricas o ambientales'
        elsif dato == 40 ; 'Objetos o sustancias calientes'
        elsif dato == 41 ; 'Objetos o sustancias frías'
        elsif dato == 42 ; 'Por inhalación'
        elsif dato == 43 ; 'Por ingestión'
        elsif dato == 44 ; 'Por absorción'
        elsif dato == 45 ; 'Secreciones líquidas corporales'
        elsif dato == 46 ; 'Líquidos contaminados o líquidos que han estado en contacto con pacientes'
        elsif dato == 47 ; 'Accidente de aviación'
        elsif dato == 48 ; 'Accidentes de buses'
        elsif dato == 49 ; 'Accidente de barco o botes'
        elsif dato == 50 ; 'Accidente de tranvías o trenes subterráneos'
        elsif dato == 51 ; 'Accidente de taxis'
        elsif dato == 52 ; 'Accidente de trenes'
        elsif dato == 53 ; 'Accidente de vehículos públicos no especificados en otra parte'
        elsif dato == 54 ; 'Con un vehículo que se mueve en dirección contraria por el mismo camino, calle o carretera'
        elsif dato == 55 ; 'Con un vehículo que se mueve en la misma dirección, en el mismo camino,  calle o carretera'
        elsif dato == 56 ; 'Con un vehículo que se mueve en una carretera de intersección o cruce'
        elsif dato == 57 ; 'Precipitarse contra o rozar lateralmente con un vehículo u objeto parado en la vía'
        elsif dato == 58 ; 'Precipitarse contra o rozar lateralmente con un vehículo u objeto parado a un lado de la vía'
        elsif dato == 59 ; 'Ser golpeado por otro vehículo mientras está parado en la vía'
        elsif dato == 60 ; 'Ser  golpeado por otro vehículo mientras se está parado fuera de la vía'
        elsif dato == 61 ; 'Otros accidentes con choques no especificados'
        elsif dato == 62 ; 'Volcarse'
        elsif dato == 63 ; 'Salirse fuera de la vía (sin control)'
        elsif dato == 64 ; 'Parada o arranque intempestivo (que lance a los ocupantes fuera o contra partes interiores del vehículo o lance el contenido del vehículo contra los ocupantes)'
        elsif dato == 65 ; 'Otros accidentes sin choque'
        elsif dato == 66 ; 'Tipos de accidentes, no especificados en otra parte'
        elsif dato == 67 ; 'No clasificado, datos insuficientes'
        end
    end    

end
